# Generated by Django 2.2.10 on 2020-06-10 03:29

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('celular', models.CharField(default='0', max_length=50, verbose_name='Celular')),
                ('direccion', models.CharField(default='', max_length=150, verbose_name='Dirección')),
                ('ciudad', models.CharField(choices=[('La paz', 'La Paz'), ('El Alto', 'El Alto')], default='La Paz', max_length=50, verbose_name='Ciudad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito_fecha_creacion', models.DateField(auto_now=True)),
                ('carrito_vendido', models.BooleanField(default=False)),
                ('carrito_estado', models.CharField(max_length=50, verbose_name='Carrito Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('producto_marca', models.CharField(max_length=50, verbose_name='Marca Producto')),
                ('producto_modelo', models.CharField(max_length=50, verbose_name='Modelo Producto')),
                ('producto_precio', models.CharField(max_length=50, verbose_name='Precio Producto')),
                ('producto_calificacion', models.CharField(max_length=50, verbose_name='Calificacion Producto')),
                ('producto_fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha Creación')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_costo_total', models.CharField(max_length=50, verbose_name='Costo Total')),
                ('venta_fecha_venta', models.DateField(auto_now=True, verbose_name='Fecha Venta')),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_f.Carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocion_nombre', models.CharField(max_length=50, verbose_name='Nombre Promoción')),
                ('promocion_descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('promocion_fecha_creacion', models.CharField(max_length=50, verbose_name='Fecha Creación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_f.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Foto_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_foto', models.ImageField(default='fotos/productos/none.jpeg', upload_to='fotos/productos/', verbose_name='Producto Foto')),
                ('foto_descripcion', models.CharField(default='', max_length=50, verbose_name='Descripcion')),
                ('foto_fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha Creación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_f.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_has_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=50, verbose_name='Cantidad')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_f.Carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_f.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ManyToManyField(through='app_f.Carrito_has_Producto', to='app_f.Producto'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
