# Generated by Django 2.2.10 on 2020-06-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_f', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_calificacion',
            field=models.CharField(default='Bueno', max_length=50, verbose_name='Calificacion Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_marca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_modelo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Modelo Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_precio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Precio Producto'),
        ),
    ]
